name: RPM build
on: [push]
jobs:
  gear-rpm-build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [alt-sisyphus, alt-p11]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install build tools and deps
        run: |
          apt-get update && apt-get install -y gear rpm-build su
          grep BuildRequires *.spec | cut -d' ' -f2 | xargs apt-get install -y

      - name: Setup builder user
        run: |
          useradd builder
          usermod -aG rpm builder
          chown -R builder:builder .

      - name: Build RPM package using gear and hasher
        run: |
          su -l -c "cd /workspace/${{ github.repository }} && gear-rpm -ba" builder
