#!/bin/sh

FACILITIES_DIR=/etc/control.d/facilities
CONTROL=/usr/sbin/control

control(){
    $CONTROL $@ #2>/dev/null
}

join(){
    readarray -t data
    local IFS=,
    echo "${data[*]}"
}


case "$1" in
    list) control | sed 's/ .*//g' ;;

    list-all)
        echo -n '['

        for f in "$FACILITIES_DIR"/*
        do
            name="${f##*/}"
            list=`control $name list | xargs printf '%s\n' | jq -R . | jq -s .`
            status=`control $name status | jq -R .`
            summary=`control $name summary | jq -R .`
            help=`control $name help | jq -R . | jq -s .`

            cat << EOF | jq -c
{
"name": "$name",
"list": $list,
"status": $status,
"summary": $summary,
"help": $help
}
EOF
        done | join
        echo -n ']'
    ;;

    values) control "$2" list | sed 's/ /\n/g' ;;

    *)
        echo "unknown command" > /dev/stderr
        exit 1
    ;;
esac
