#!/bin/bash -e

_completion_actl() {
    mapfile -t COMPREPLY < <(compgen -W "$(COMP_CWORD="${COMP_CWORD}" COMP_WORDS="${COMP_WORDS[@]:0:${COMP_CWORD}}" /usr/share/alteratorctl/scripts/completion_wrapper "${1}" "${2}" "${3}")" -- "$2")
}

complete -o nosort -F _completion_actl alteratorctl
complete -o nosort -F _completion_actl actl
