%define _unpackaged_files_terminate_build 1

Name: alterator-backend-control
Version: 0.1.0
Release: alt1

Summary: Alterator interface for system restrictions management
License: GPLv2+
Group: Other
URL: https://altlinux.space/alt/altrerator-backend-control

BuildArch: noarch

BuildRequires(Pre): rpm-macros-alterator

Source0: %name-%version.tar

%description
Alterator interface for system restrictions management.

%package -n alterator-interface-control
Summary: XML files for org.altlinux.alterator.control1 interface
Group: System/Configuration/Other
Version: 0.1.0
Release: alt1

%description -n alterator-interface-control
XML files describing D-Bus interface org.altlinux.alterator.control1.


%prep
%setup

%install

mkdir -p %buildroot%_datadir/dbus-1/interfaces
mkdir -p %buildroot%_datadir/polkit-1/actions
mkdir -p %buildroot%_sysconfdir/alterator/control

mkdir -p %buildroot%_alterator_datadir/backends
mkdir -p %buildroot%_alterator_datadir/objects
mkdir -p %buildroot%_alterator_datadir/control

install -vpDm 644 control1/org.altlinux.alterator.control1.xml    %buildroot%_datadir/dbus-1/interfaces/org.altlinux.alterator.control1.xml
install -vpDm 644 control1/org.altlinux.alterator.control1.policy %buildroot%_datadir/polkit-1/actions/org.altlinux.alterator.control1.policy

install -vpDm 644 batch_control/org.altlinux.alterator.batch_control1.xml    %buildroot%_datadir/dbus-1/interfaces/org.altlinux.alterator.batch_control1.xml
install -vpDm 644 batch_control/org.altlinux.alterator.batch_control1.policy %buildroot%_datadir/polkit-1/actions/org.altlinux.alterator.batch_control1.policy

install -vpDm 755 %name.filetrigger                               %buildroot%_rpmlibdir/10-%name.filetrigger

install -vpDm 755 control1/control-entry-generator                %buildroot%_libexecdir/%name/control-entry-generator
install -vpDm 644 control1/facility.backend.template              %buildroot%_libexecdir/%name/facility.backend.template
install -vpDm 644 control1/control-whitelist                      %buildroot%_libexecdir/%name/whitelist
cp -r             control1/overrides                              %buildroot%_libexecdir/%name/overrides

find %buildroot%_libexecdir/%name/overrides/ -type f -name '*\.policy' -print0 |
    xargs -0 ln -srt %buildroot%_datadir/polkit-1/actions/

install -vpDm 644 batch_control/control.object                    %buildroot%_alterator_datadir/objects
install -vpDm 644 batch_control/control.backend                   %buildroot%_alterator_datadir/backends
install -vpDm 755 batch_control/control-helper                    %buildroot%_libexecdir/%name/control-helper


%files
%dir %_sysconfdir/alterator/control
%dir %_alterator_datadir/control
%dir %_alterator_datadir/objects
%dir %_alterator_datadir/backends
%_alterator_datadir/objects/control.object
%_alterator_datadir/backends/control.backend
%_libexecdir/%name/control-helper
%_libexecdir/%name/control-entry-generator
%_libexecdir/%name/whitelist
%_libexecdir/%name/facility.backend.template
%_libexecdir/%name/overrides/*
%_rpmlibdir/10-%name.filetrigger


%files -n alterator-interface-control
%_datadir/dbus-1/interfaces/*
%_datadir/polkit-1/actions/*

%post
%_libexecdir/%name/control-entry-generator

%postun
if [ $1 = 0 ]; then
    find %_sysconfdir/alterator/control  -name "autogenerated-control-*.control" -type f -print0 | xargs -0 rm -f '{}' ||:
    find %_sysconfdir/alterator/backends -name "autogenerated-control-*.backend" -type f -print0 | xargs -0 rm -f '{}' ||:
fi

%changelog
* Tue Mar 18 2025 Andrey Alekseev <parovoz@altlinux.org> 0.1.0-alt1
- initial build
